#!/usr/bin/env bash

if [ -f /opt/PiliPlus/piliplus.launcher ]; then
  install -m 755 /opt/PiliPlus/piliplus.launcher /usr/bin/piliplus
fi

chmod 755 /opt/PiliPlus/piliplus 2>/dev/null || true

if [ "$1" = "configure" ] && [ -x /usr/bin/update-mime-database ]; then
    echo "updating mime database..."
    update-mime-database /usr/share/mime || true
fi

if [ "$1" = "configure" ] && [ -x /usr/bin/gtk-update-icon-cache ]; then
    echo "updating icon cache..."
    gtk-update-icon-cache -q -f -t /usr/share/icons/hicolor || true
fi

if [ "$1" = "configure" ] && [ -x /usr/bin/update-desktop-database ]; then
    echo "configure desktop database..."
    update-desktop-database -q /usr/share/applications || true
fi

exit 0
